// Backlog HiPe Kids v6.0.0 (FR) — seed du 1er espace client. Généré depuis le xlsx. @Rabah 2026-08-05
export const HIPEKIDS_BACKLOG = [
 {
  "code": "AA-BE-0201",
  "section": "A · SOCLE BACKEND CENTRAL (débloque tout — à faire en premier)",
  "title": "Persister le profil de mission de l'enfant (endpoint unique, 6 missions)",
  "story": "En tant que système, je veux un endpoint unique qui persiste chaque payload de mission, afin que le rapport d'évaluation lise de vraies données enregistrées au lieu du localStorage.",
  "area": "PA",
  "priority": 5,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "4 j"
 },
 {
  "code": "AA-BE-0202",
  "section": "A · SOCLE BACKEND CENTRAL (débloque tout — à faire en premier)",
  "title": "Créer l'évaluation côté serveur à la complétion du hub (LE PLUS BLOQUANT)",
  "story": "En tant que système, je veux que compléter les 6 missions crée une vraie évaluation, afin que l'enfant passe de « rapport prêt » à « actif ».",
  "area": "PA",
  "priority": 5,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "AA-BE-0201",
  "estimate": "3 j"
 },
 {
  "code": "AA-BE-0203",
  "section": "A · SOCLE BACKEND CENTRAL (débloque tout — à faire en premier)",
  "title": "Déplacer l'algorithme de recommandation vers le backend (Moteur 1 + Moteur 2)",
  "story": "En tant que plateforme, je veux que la recommandation de rythme/durée/volume soit calculée côté serveur, afin que la logique métier ne soit pas exposée ni dupliquée sur le front.",
  "area": "SH",
  "priority": 5,
  "category": "Refactorisation",
  "status": "todo",
  "dependsOn": "AA-BE-0201",
  "estimate": "4 j"
 },
 {
  "code": "AA-BE-0204",
  "section": "A · SOCLE BACKEND CENTRAL (débloque tout — à faire en premier)",
  "title": "Magasin de contenu i18n côté serveur pour le rapport & les libellés de mission",
  "story": "En tant que parent dans n'importe quelle langue, je veux que le texte du rapport et les libellés d'options soient résolus de façon cohérente, afin que le document soit correct dans toutes les langues.",
  "area": "SH",
  "priority": 4,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "AA-BE-0201",
  "estimate": "3 j"
 },
 {
  "code": "AA-BE-0210",
  "section": "B · DONNÉES ENFANTS / PROGRESSION (vraies données derrière les nouveaux écrans)",
  "title": "Champs agrégés légers par enfant pour la liste des enfants",
  "story": "En tant que parent, je veux que chaque carte enfant affiche une vraie régularité, les cours à venir et l'état « zéro cours », afin que la liste reflète la réalité sans N appels.",
  "area": "PA",
  "priority": 5,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "2 j"
 },
 {
  "code": "AA-BE-0211",
  "section": "B · DONNÉES ENFANTS / PROGRESSION (vraies données derrière les nouveaux écrans)",
  "title": "Historique de progression & intégrité des points",
  "story": "En tant que parent, je veux un graphique de progression et un historique de niveau exacts, afin que la timeline reflète le vrai parcours de mon enfant.",
  "area": "PA",
  "priority": 4,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "3 j"
 },
 {
  "code": "AA-BE-0212",
  "section": "B · DONNÉES ENFANTS / PROGRESSION (vraies données derrière les nouveaux écrans)",
  "title": "Faire respecter la limite de 8 enfants + exposer les évaluations héritées",
  "story": "En tant que système, je veux la limite d'enfants respectée et les évaluations héritées exposées, afin que les règles tiennent côté serveur et que les enfants de l'ancien flux obtiennent quand même un rapport.",
  "area": "PA",
  "priority": 3,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "1,5 j"
 },
 {
  "code": "AA-BE-0220",
  "section": "C · INSCRIPTION / AUTH / CONFORMITÉ (manques backend)",
  "title": "completeStep3 : persister knownUsDetail + referralCode ; vérifier reCAPTCHA",
  "story": "En tant que système, je veux les données d'acquisition stockées et reCAPTCHA vérifié, afin que l'attribution fonctionne et que l'abus soit bloqué côté serveur.",
  "area": "PA",
  "priority": 5,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "1,5 j"
 },
 {
  "code": "AA-BE-0221",
  "section": "C · INSCRIPTION / AUTH / CONFORMITÉ (manques backend)",
  "title": "Vérification email & téléphone à l'inscription",
  "story": "En tant que système, je veux un email et un téléphone vérifiés, afin de réduire les faux contacts (coût réel sur les évaluations non honorées).",
  "area": "PA",
  "priority": 4,
  "category": "Conformité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "2,5 j"
 },
 {
  "code": "AA-FE-0230",
  "section": "D · FRONTEND — déjà construit sur cette branche (référence / périmètre de régression, BE minimal)",
  "title": "Refonte inscription 8 écrans + reCAPTCHA login",
  "story": "En tant que nouveau parent, je veux une inscription guidée claire, afin que l'onboarding inspire confiance.",
  "area": "PA",
  "priority": 5,
  "category": "Amélioration - UX/UI",
  "status": "built",
  "dependsOn": "voir dép. BE",
  "estimate": "Construit"
 },
 {
  "code": "AA-FE-0231",
  "section": "D · FRONTEND — déjà construit sur cette branche (référence / périmètre de régression, BE minimal)",
  "title": "PageHeader partagé + rafraîchissement Dashboard",
  "story": "En tant que parent, je veux des en-têtes cohérents et un dashboard clair.",
  "area": "PA",
  "priority": 3,
  "category": "Amélioration - UX/UI",
  "status": "built",
  "dependsOn": "voir dép. BE",
  "estimate": "Construit"
 },
 {
  "code": "AA-FE-0232",
  "section": "D · FRONTEND — déjà construit sur cette branche (référence / périmètre de régression, BE minimal)",
  "title": "Reconstruction de la page Progression",
  "story": "En tant que parent, je veux une timeline de niveau claire et un graphique de cours.",
  "area": "PA",
  "priority": 4,
  "category": "Amélioration - UX/UI",
  "status": "built",
  "dependsOn": "voir dép. BE",
  "estimate": "Construit"
 },
 {
  "code": "AA-FE-0233",
  "section": "D · FRONTEND — déjà construit sur cette branche (référence / périmètre de régression, BE minimal)",
  "title": "Reconstruction « Mes enfants » + cartes enfant (5 états)",
  "story": "En tant que parent, je veux des cartes enfant claires avec le bon état et les bonnes actions.",
  "area": "PA",
  "priority": 5,
  "category": "Amélioration - UX/UI",
  "status": "built",
  "dependsOn": "voir dép. BE",
  "estimate": "Construit"
 },
 {
  "code": "AA-FE-0234",
  "section": "D · FRONTEND — déjà construit sur cette branche (référence / périmètre de régression, BE minimal)",
  "title": "Cœur du Quiz Hub + contrat de persistance + composants partagés",
  "story": "En tant que parent, je veux un hub de missions soigné qui ne perd jamais mes réponses.",
  "area": "PA",
  "priority": 5,
  "category": "Amélioration - UX/UI",
  "status": "built",
  "dependsOn": "voir dép. BE",
  "estimate": "Construit"
 },
 {
  "code": "AA-FE-0235",
  "section": "D · FRONTEND — déjà construit sur cette branche (référence / périmètre de régression, BE minimal)",
  "title": "6 missions (Infos de base, Intérêts, Personnalité, Style d'apprentissage, Objectifs, Test de niveau)",
  "story": "En tant que parent, je veux chaque mission claire, juste et correcte selon l'âge/le genre.",
  "area": "PA",
  "priority": 5,
  "category": "Amélioration - UX/UI",
  "status": "built",
  "dependsOn": "voir dép. BE",
  "estimate": "Construit"
 },
 {
  "code": "AA-FE-0236",
  "section": "D · FRONTEND — déjà construit sur cette branche (référence / périmètre de régression, BE minimal)",
  "title": "Rapport d'évaluation — composant imprimable 2 pages + données Can-Do/conseils",
  "story": "En tant que parent, je veux un rapport personnalisé de 2 pages prouvant que HiPe Kids comprend mon enfant.",
  "area": "PA",
  "priority": 5,
  "category": "Amélioration - UX/UI",
  "status": "built",
  "dependsOn": "voir dép. BE",
  "estimate": "Construit"
 },
 {
  "code": "AA-FE-0240",
  "section": "E · POINTS OUVERTS (cette session)",
  "title": "Brouillon de profil non chargé — clé studentId incohérente",
  "story": "En tant que parent, je veux que le rapport charge les données enregistrées de mon enfant, afin qu'il ne soit jamais vide après avoir terminé les missions.",
  "area": "PA",
  "priority": 5,
  "category": "Bug",
  "status": "done",
  "dependsOn": "",
  "estimate": "Fait"
 },
 {
  "code": "AA-FE-0241",
  "section": "E · POINTS OUVERTS (cette session)",
  "title": "Nettoyage code mort & i18n",
  "story": "En tant qu'équipe, je veux le code mort supprimé et le FR en dur traduit, afin que le codebase reste propre.",
  "area": "SH",
  "priority": 2,
  "category": "Refactorisation",
  "status": "todo",
  "dependsOn": "",
  "estimate": "1 j"
 },
 {
  "code": "AA-FE-0242",
  "section": "E · POINTS OUVERTS (cette session)",
  "title": "Fusion échelle CECR : A2 Key intégré dans A2",
  "story": "En tant que plateforme, je veux une échelle CECR de 7 niveaux fidèle à Cambridge, afin que les parents ne voient jamais un niveau inexistant dans le cadre officiel.",
  "area": "SH",
  "priority": 4,
  "category": "Refactorisation",
  "status": "done",
  "dependsOn": "",
  "estimate": "Fait"
 },
 {
  "code": "AA-BE-0301",
  "section": "F · BOUTIQUE / PAIEMENT (chemin du revenu — priorité business la plus haute)",
  "title": "Source de vérité tarifaire + endpoint de devis pour le configurateur",
  "story": "En tant que plateforme, je veux les prix calculés côté serveur, afin que la Boutique n'affiche jamais un prix que le backend n'honorerait pas.",
  "area": "PA",
  "priority": 5,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "3 j"
 },
 {
  "code": "AA-BE-0302",
  "section": "F · BOUTIQUE / PAIEMENT (chemin du revenu — priorité business la plus haute)",
  "title": "Paiement Stripe pour les paniers du configurateur (abonnements + packs)",
  "story": "En tant que parent, je veux payer l'offre configurée, afin que mon enfant puisse réellement commencer.",
  "area": "PA",
  "priority": 5,
  "category": "Intégration",
  "status": "todo",
  "dependsOn": "AA-BE-0301",
  "estimate": "5 j"
 },
 {
  "code": "AA-BE-0303",
  "section": "F · BOUTIQUE / PAIEMENT (chemin du revenu — priorité business la plus haute)",
  "title": "Provisioning post-paiement : crédits, portefeuille, dates d'engagement",
  "story": "En tant que système, je veux qu'un paiement réussi crédite le portefeuille au niveau du compte, afin que le parent puisse réserver immédiatement.",
  "area": "PA",
  "priority": 5,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "AA-BE-0302",
  "estimate": "3 j"
 },
 {
  "code": "AA-BE-0304",
  "section": "F · BOUTIQUE / PAIEMENT (chemin du revenu — priorité business la plus haute)",
  "title": "Endpoint des offres promotionnelles (remplace mockOffers.js)",
  "story": "En tant que marketing, je veux publier de vraies offres saisonnières, afin que les campagnes fonctionnent sans déploiement.",
  "area": "PA",
  "priority": 3,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "3 j"
 },
 {
  "code": "AA-BE-0310",
  "section": "G · RÉSERVATIONS (la création de réservation est actuellement DÉSACTIVÉE pour les vrais comptes)",
  "title": "Activer la création de réservation réelle (panier multi-cours)",
  "story": "En tant que parent avec des crédits, je veux réserver des cours, afin que mon enfant prenne réellement des leçons.",
  "area": "PA",
  "priority": 5,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "AA-BE-0303",
  "estimate": "4 j"
 },
 {
  "code": "AA-BE-0311",
  "section": "G · RÉSERVATIONS (la création de réservation est actuellement DÉSACTIVÉE pour les vrais comptes)",
  "title": "Flux d'annulation + règles de restitution des crédits",
  "story": "En tant que parent, je veux annuler un cours réservé selon des règles claires, afin de savoir quand mon crédit revient.",
  "area": "PA",
  "priority": 4,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "2,5 j"
 },
 {
  "code": "AA-BE-0312",
  "section": "G · RÉSERVATIONS (la création de réservation est actuellement DÉSACTIVÉE pour les vrais comptes)",
  "title": "Vraies disponibilités professeurs fusionnées pour le calendrier de réservation",
  "story": "En tant que parent, je veux voir de vrais créneaux disponibles, afin que ce que je réserve existe réellement.",
  "area": "PA",
  "priority": 4,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "2,5 j"
 },
 {
  "code": "AA-BE-0320",
  "section": "H · PARRAINAGE (front entièrement construit, tourne sur données factices sorties le 2026-08-05)",
  "title": "Cœur du parrainage : codes, suivi des filleuls, fenêtre de bénéfice",
  "story": "En tant que parent, je veux que mon code de parrainage suive réellement les inscriptions, afin de gagner mes récompenses.",
  "area": "PA",
  "priority": 3,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "",
  "estimate": "3 j"
 },
 {
  "code": "AA-BE-0321",
  "section": "H · PARRAINAGE (front entièrement construit, tourne sur données factices sorties le 2026-08-05)",
  "title": "Récompenses de l'échelle de paliers + retrait",
  "story": "En tant que parent, je veux que mes récompenses de palier soient appliquées, afin que parrainer des amis en vaille la peine.",
  "area": "PA",
  "priority": 3,
  "category": "Nouvelle fonctionnalité",
  "status": "todo",
  "dependsOn": "AA-BE-0320",
  "estimate": "2,5 j"
 }
];
export default HIPEKIDS_BACKLOG;
